### ISSUE TITLE
Picture in Readme is broken

### ISSUE THREAD

**Issue by HanningLin** [rootsongjc/cloud-native-sandbox#5]
# Environment

- OS:
- Kubernetes version:
- Docker version:

## What I did?

Your operations on this repo.

## Messages

Logs or error messages.

Here is a picture.
![image](https://user-images.githubusercontent.com/20200205/114476295-cf54fb80-9bae-11eb-9fb1-0a9793e66549.png)

**Comment by rootsongjc** [comment]
This picture is lost, I can't find it. So delete the picture from README.
